// <auto-generated />
using System;
using LightupFactoryService.ContextStr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightupFactoryService.Migrations
{
    [DbContext(typeof(LightUpFactoryContext))]
    [Migration("20210823062208_capaadded")]
    partial class capaadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LightupFactoryService.Model.Aqllevel", b =>
                {
                    b.Property<string>("Aqllevelid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aqllevelname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnterpriseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filtertags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Is_Delete")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Locked")
                        .HasColumnType("int");

                    b.Property<int?>("Isfrozen")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Aqllevelid");

                    b.ToTable("Aqllevel");
                });

            modelBuilder.Entity("LightupFactoryService.Model.Capa", b =>
                {
                    b.Property<string>("Capaid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Attachmentsid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Briefdescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capacustomdataid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Capaname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Carresolutionaction")
                        .HasColumnType("int");

                    b.Property<string>("Carseverityid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("Cdotypeid")
                        .HasColumnType("int");

                    b.Property<int?>("Changecount")
                        .HasColumnType("int");

                    b.Property<string>("Classificationid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Closedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Closedategmt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Closedbyid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Closedescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnterpriseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initiatorid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initiatororganizationid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Is_Delete")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Locked")
                        .HasColumnType("int");

                    b.Property<int?>("Isfrozen")
                        .HasColumnType("int");

                    b.Property<int?>("Issubmitted")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Occurrencedate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Occurrencedategmt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Organizationid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origprocessmodeltemplateid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ownerid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioritylevelid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processmodelid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proposedresolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualityresolutioncodeid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Reporteddate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Reporteddategmt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reporterid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reporterorganizationid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Riskassessmentid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roleid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subclassificationid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Systemicissue")
                        .HasColumnType("int");

                    b.Property<int?>("Triagecomplete")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Capaid");

                    b.ToTable("Capa");
                });
#pragma warning restore 612, 618
        }
    }
}
