// <auto-generated />
using System;
using LightupFactoryService.ContextStr;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightupFactoryService.Migrations
{
    [DbContext(typeof(LightUpFactoryContext))]
    [Migration("20210823054146_IntialStructure")]
    partial class IntialStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LightupFactoryService.Model.Aqllevel", b =>
                {
                    b.Property<string>("Aqllevelid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aqllevelname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnterpriseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filtertags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Is_Delete")
                        .HasColumnType("int");

                    b.Property<int?>("Is_Locked")
                        .HasColumnType("int");

                    b.Property<int?>("Isfrozen")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Aqllevelid");

                    b.ToTable("Aqllevel");
                });
#pragma warning restore 612, 618
        }
    }
}
